spring.application.name=PXLActivityTracker
server.port=8081
# update datasource information here
spring.datasource.url=jdbc:mysql://localhost:3306/activityTracker-db
spring.datasource.username=user
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=update

# update nutrionix information here
nutritionix.app.id=b60e74d9
nutritionix.app.key=6cfb58ffa5d02c557111c24e2fabd298
nutritionix.api.url=https://trackapi.nutritionix.com/v2/natural/exercise
