spring.h2.console.enabled=true
spring.jpa.show-sql=true

# je mag eigenschappen toevoegen indien nodig
# onderstaande properties mag je niet aanpassen of verwijderen
server.error.include-message=always
spring.jpa.hibernate.ddl-auto=create
spring.jpa.defer-datasource-initialization=true

server.port=8081
