// <auto-generated />
using System;
using AlienAdoptionAgency.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AlienAdoptionAgency.Infrastructure.Migrations
{
    [DbContext(typeof(AgencyDbContext))]
    [Migration("20250120132942_SeedData")]
    partial class SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AlienAdoptionAgency.Domain.AdoptionRequest", b =>
                {
                    b.Property<int>("AdoptionRequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AdoptionRequestId"));

                    b.Property<int>("AlienId")
                        .HasColumnType("int");

                    b.Property<string>("ApplicantEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ApplicantName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReasonForAdoption")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RequestDate")
                        .HasColumnType("datetime2");

                    b.HasKey("AdoptionRequestId");

                    b.HasIndex("AlienId");

                    b.ToTable("AdoptionRequests");

                    b.HasData(
                        new
                        {
                            AdoptionRequestId = 1,
                            AlienId = 5,
                            ApplicantEmail = "professor.quasar@cosmos.edu",
                            ApplicantName = "Professor Quasar",
                            ReasonForAdoption = "Wants to study Floopticons in a low-gravity lab.",
                            RequestDate = new DateTime(2024, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AdoptionRequestId = 2,
                            AlienId = 8,
                            ApplicantEmail = "captain.nebula@galaxynet.space",
                            ApplicantName = "Captain Nebula",
                            ReasonForAdoption = "Loves bubble art and wants to host exhibitions.",
                            RequestDate = new DateTime(2024, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AdoptionRequestId = 3,
                            AlienId = 12,
                            ApplicantEmail = "dr.ooze@slimeworld.science",
                            ApplicantName = "Dr. Ooze",
                            ReasonForAdoption = "Wants to study the unique slippery properties for science.",
                            RequestDate = new DateTime(2024, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AdoptionRequestId = 4,
                            AlienId = 15,
                            ApplicantEmail = "contact@galaxygroomers.space",
                            ApplicantName = "Galaxy Groomers Inc.",
                            ReasonForAdoption = "Perfect mascot for their alien grooming business.",
                            RequestDate = new DateTime(2024, 12, 5, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AdoptionRequestId = 5,
                            AlienId = 18,
                            ApplicantEmail = "nimbus.support@skypark.quaz",
                            ApplicantName = "Nimbus Skypark",
                            ReasonForAdoption = "Wants an attraction for floating aliens.",
                            RequestDate = new DateTime(2024, 10, 28, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AdoptionRequestId = 6,
                            AlienId = 22,
                            ApplicantEmail = "fred.fidgets@funland.quaz",
                            ApplicantName = "Fidgety Fred",
                            ReasonForAdoption = "Wants a wiggly companion for his entertainment park.",
                            RequestDate = new DateTime(2024, 11, 22, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("AlienAdoptionAgency.Domain.Alien", b =>
                {
                    b.Property<int>("AlienId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AlienId"));

                    b.Property<string>("FavoriteSnack")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAdoptable")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Planet")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SpecialNeeds")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Species")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AlienId");

                    b.ToTable("Aliens");

                    b.HasData(
                        new
                        {
                            AlienId = 1,
                            FavoriteSnack = "Asteroid Soup",
                            IsAdoptable = true,
                            Name = "Blorp",
                            Planet = "Gloop-7",
                            SpecialNeeds = "Moisture-rich environment",
                            Species = "Squigglenaut"
                        },
                        new
                        {
                            AlienId = 2,
                            FavoriteSnack = "Space Jelly",
                            IsAdoptable = true,
                            Name = "Zzork",
                            Planet = "Nebula-42",
                            SpecialNeeds = "Dislikes sunlight",
                            Species = "Blobulous"
                        },
                        new
                        {
                            AlienId = 3,
                            FavoriteSnack = "Nebula Nectar",
                            IsAdoptable = true,
                            Name = "Fizzle",
                            Planet = "Stardust-5",
                            SpecialNeeds = "Needs glitter for energy",
                            Species = "Glitterbug"
                        },
                        new
                        {
                            AlienId = 4,
                            FavoriteSnack = "Meteor Bites",
                            IsAdoptable = true,
                            Name = "Glorp",
                            Planet = "Quazar-9",
                            SpecialNeeds = "Prefers low gravity",
                            Species = "Spikydoodle"
                        },
                        new
                        {
                            AlienId = 5,
                            FavoriteSnack = "Stardust Wafers",
                            IsAdoptable = false,
                            Name = "Zizzle",
                            Planet = "Nebulon-12",
                            SpecialNeeds = "Requires a constant supply of sparkling water",
                            Species = "Floopticon"
                        },
                        new
                        {
                            AlienId = 6,
                            FavoriteSnack = "Comet Chips",
                            IsAdoptable = true,
                            Name = "Borko",
                            Planet = "Glimmerfall",
                            SpecialNeeds = "Needs a UV-safe habitat",
                            Species = "Tentapuff"
                        },
                        new
                        {
                            AlienId = 7,
                            FavoriteSnack = "Magnetic Pebbles",
                            IsAdoptable = true,
                            Name = "Clink",
                            Planet = "Titanium-X",
                            SpecialNeeds = "Occasionally needs an oil bath",
                            Species = "Metalion"
                        },
                        new
                        {
                            AlienId = 8,
                            FavoriteSnack = "Nebula Gummies",
                            IsAdoptable = false,
                            Name = "Snorblat",
                            Planet = "Sticky-2",
                            SpecialNeeds = "Allergic to plastic",
                            Species = "Bubblegumpher"
                        },
                        new
                        {
                            AlienId = 9,
                            FavoriteSnack = "Electric Eclairs",
                            IsAdoptable = true,
                            Name = "Fizzle",
                            Planet = "Electrovoid",
                            SpecialNeeds = "Emits small electric shocks when happy",
                            Species = "Zapwhisker"
                        },
                        new
                        {
                            AlienId = 10,
                            FavoriteSnack = "Liquid Pops",
                            IsAdoptable = true,
                            Name = "Wobble",
                            Planet = "Jiggleprime",
                            SpecialNeeds = "Must stay hydrated to maintain form",
                            Species = "Gelatinian"
                        },
                        new
                        {
                            AlienId = 11,
                            FavoriteSnack = "Photon Crunch",
                            IsAdoptable = true,
                            Name = "Krizzle",
                            Planet = "Orbit-X",
                            SpecialNeeds = "Noisy during full moons",
                            Species = "Quarkbat"
                        },
                        new
                        {
                            AlienId = 12,
                            FavoriteSnack = "Galactic Gels",
                            IsAdoptable = false,
                            Name = "Blibble",
                            Planet = "Slimeathos",
                            SpecialNeeds = "Extremely slippery",
                            Species = "Oozalian"
                        },
                        new
                        {
                            AlienId = 13,
                            FavoriteSnack = "Swirly Sticks",
                            IsAdoptable = true,
                            Name = "Squizzle",
                            Planet = "Dizzydome",
                            SpecialNeeds = "Spins uncontrollably when nervous",
                            Species = "Spinaxian"
                        },
                        new
                        {
                            AlienId = 14,
                            FavoriteSnack = "Solar Beans",
                            IsAdoptable = true,
                            Name = "Zobbit",
                            Planet = "Hyperflora",
                            SpecialNeeds = "Needs to be constantly moving",
                            Species = "Nimbletooth"
                        },
                        new
                        {
                            AlienId = 15,
                            FavoriteSnack = "Fluffy Cakes",
                            IsAdoptable = false,
                            Name = "Frizzle",
                            Planet = "Hairyworld",
                            SpecialNeeds = "Requires regular grooming",
                            Species = "Poofian"
                        },
                        new
                        {
                            AlienId = 16,
                            FavoriteSnack = "Shimmering Treats",
                            IsAdoptable = true,
                            Name = "Glitz",
                            Planet = "Shiny-P3",
                            SpecialNeeds = "Sheds glitter daily",
                            Species = "Glitterhug"
                        },
                        new
                        {
                            AlienId = 17,
                            FavoriteSnack = "Asteroid Bars",
                            IsAdoptable = true,
                            Name = "Plorb",
                            Planet = "Craterholm",
                            SpecialNeeds = "Can’t jump",
                            Species = "Chunkaphant"
                        },
                        new
                        {
                            AlienId = 18,
                            FavoriteSnack = "Sky Bites",
                            IsAdoptable = false,
                            Name = "Fuzzle",
                            Planet = "Nimbus-V",
                            SpecialNeeds = "Floats unpredictably",
                            Species = "Hoverbeast"
                        },
                        new
                        {
                            AlienId = 19,
                            FavoriteSnack = "Prickly Pears",
                            IsAdoptable = true,
                            Name = "Grum",
                            Planet = "Cactarion",
                            SpecialNeeds = "Sensitive to loud noises",
                            Species = "Spikeback"
                        },
                        new
                        {
                            AlienId = 20,
                            FavoriteSnack = "Zappy Zips",
                            IsAdoptable = true,
                            Name = "Zapra",
                            Planet = "Thunderspire",
                            SpecialNeeds = "Prone to static buildup",
                            Species = "Bolt Hopper"
                        },
                        new
                        {
                            AlienId = 21,
                            FavoriteSnack = "Gear Biscuits",
                            IsAdoptable = true,
                            Name = "Klinkle",
                            Planet = "Cognium-9",
                            SpecialNeeds = "Loves puzzles",
                            Species = "Gearclink"
                        },
                        new
                        {
                            AlienId = 22,
                            FavoriteSnack = "Gloop Worms",
                            IsAdoptable = false,
                            Name = "Floopy",
                            Planet = "Jellycross",
                            SpecialNeeds = "Extremely wiggly",
                            Species = "Wiggleworm"
                        },
                        new
                        {
                            AlienId = 23,
                            FavoriteSnack = "Bite-sized Moons",
                            IsAdoptable = true,
                            Name = "Quibble",
                            Planet = "Fidgetron",
                            SpecialNeeds = "Chews on everything",
                            Species = "Nibblenot"
                        });
                });

            modelBuilder.Entity("AlienAdoptionAgency.Domain.AdoptionRequest", b =>
                {
                    b.HasOne("AlienAdoptionAgency.Domain.Alien", "Alien")
                        .WithMany()
                        .HasForeignKey("AlienId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Alien");
                });
#pragma warning restore 612, 618
        }
    }
}
