version: "3.8"

services:
  birdwatching-db:
    image: postgres:16
    container_name: birdwatching-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: birdwatching_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
